# Generated by Django 5.1 on 2024-09-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('purchase_date', models.DateField()),
                ('statut', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
