# Generated by Django 5.1 on 2024-09-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
