# Generated by Django 5.1 on 2024-09-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_equipment_brand_equipment_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='serial_code',
            field=models.CharField(default='default_serial_code', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.CharField(default='default_brand', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='statut',
            field=models.CharField(max_length=50),
        ),
    ]
