# Generated by Django 5.1 on 2024-09-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_equipment_serial_code_alter_equipment_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.CharField(choices=[('Dell', 'Dell'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Apple', 'Apple'), ('Asus', 'Asus'), ('Acer', 'Acer'), ('Samsung', 'Samsung'), ('LG', 'LG'), ('Sony', 'Sony'), ('Toshiba', 'Toshiba'), ('Microsoft', 'Microsoft'), ('Huawei', 'Huawei'), ('MSI', 'MSI'), ('Razer', 'Razer'), ('Xiaomi', 'Xiaomi'), ('Gigabyte', 'Gigabyte'), ('Corsair', 'Corsair'), ('Alienware', 'Alienware'), ('ZOTAC', 'ZOTAC'), ('Logitech', 'Logitech')], max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment',
            field=models.CharField(choices=[], default='default_equipment', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='statut',
            field=models.CharField(choices=[('En Service', 'En Service'), ('En Réparation', 'En Réparation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('Machine', 'Machine'), ('Accessoire', 'Accessoire')], max_length=50),
        ),
    ]
