# Generated by Django 5.1 on 2024-09-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
