# Generated by Django 5.1 on 2024-09-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_utilisateur_date_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('equipement_id', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
